#!/usr/bin/env python3
# -*- mode: python; coding: utf-8 -*-
"""
Usage: ip2mne [OPTIONS] [IPv4 [IPv4 …]]

Positional arguments:
  IPv4                  IPv4 address

Optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show version information and exit
  -c, --copyright       show copying policy and exit
  -d DELIMITER, --delimiter DELIMITER
                        use DELIMITER instead of ‘-’

If no arguments are given, addresses are read from standard input.

Please see http://gurno.com/adam/mne/ | https://archive.is/1wiw5
for the reason this program exists.

Please report issues at https://github.com/kseistrup/ip-mnemonics
"""
##############################################################################
# This program is free software; you can redistribute it and/or modify it    #
# under the terms of the GNU General Public License as published by the Free #
# Software Foundation; either version 3 of the License, or (at your option)  #
# any later version.                                                         #
#                                                                            #
# This program is distributed in the hope that it will be useful, but with-  #
# out any warranty; without even the implied warranty of merchantability or  #
# fitness for a particular purpose. See the GNU General Public License for   #
# more details.  <http://gplv3.fsf.org/>                                     #
##############################################################################

import sys
import os
import pathlib
import argparse
import ipaddress
import pprint

try:
    from locale import (Error, setlocale, LC_ALL)
    _ = setlocale(LC_ALL, '')
except (ImportError, ModuleNotFoundError, NameError, Error):
    pass

__author__ = 'Klaus Alexander Seistrup <klaus@seistrup.dk>'
__whoami__ = 'ip2mne'
__revision__ = '2017-02-28'
__version__ = '0.0.2α ({})'.format(__revision__)
__copyright__ = """\
{progname} {version}
Copyright © 2017 Klaus Alexander Seistrup <klaus@seistrup.dk>

This is free software; see the source for copying conditions. There is no
warranty; not even for merchantability or fitness for a particular purpose.\
""".format(progname=__whoami__, version=__version__)

DEBUG = os.environ.get('DEBUG', 'False')[0].upper() in '1JTY'  # 1/Ja/True/Yes

EPILOG = """\
If no arguments are given, addresses are read from standard input.

Please see http://gurno.com/adam/mne/ | https://archive.is/1wiw5
for the reason this program exists.

Please report issues at https://github.com/kseistrup/ip-mnemonics\
"""

# http://gurno.com/adam/mne/
WORDS = """
zip ace act add age aim air and ant ape arm art ash ask bad bag
ban bar bat bay bed bet bid big bin bit bog boo box bud bug bun
bus cab can cap car cat cop cot cow cry cub cup cut day den did
die dig dim dip dog dry dub dud dug ear eat eel egg elf elk elm
end fan far fat fed few fib fig fin fit fix fly fog foo fox fry
fun gab gag gap gas gel gem get gin got gum gut had has hat hen
hex hid hip hit hog hop hot how hub hug hum hut ice ill imp ink
irk jab jam jar jaw jet jig job jog jot joy key kid kin kit lab
lag lap law lax lay leg let lid lip lit lot low mad map mat men
met mix mob moo mop mud mug nab nag nap net new nil nip nod nor
now nut oak oat odd off old orb out owl own pad pal pan pay pen
pet pie pig pin pit ply pod pop pot pox pry pun pup put rag ran
rat raw red rid rig rip rot row rub rug run rut rye sad sag sap
sat saw say set shy sip sit ski sky sly sob soy spa spy tab tag
tan tap tar tax the tie tin tip top toy try tub tug use van vat
vex vow wag war was wax web wet who wig win wit yes yet zoo all
"""
MNEMONICS = {key: val for (key, val) in enumerate(WORDS.split())}


def die(message=None):
    """Exit gracefully"""
    if message is not None:
        print(message, file=sys.stderr)
    sys.exit(1 if message else 0)


def debug(head, data):
    """Possibly pretty print an object to stderr"""
    if DEBUG:
        pprint.pprint({head: data}, stream=sys.stderr)


def ip2mne(address, delimiter='-'):
    """Construct the mnemonic associated with a given IPv4 address"""
    try:
        ipv4 = ipaddress.ip_address(address)
    except ValueError as error:
        die(error)

    if ipv4.version != 4:
        die('{} is not an IPv4 address'.format(address))

    elements = map(int, ipv4.compressed.split('.'))
    octets = (MNEMONICS[element] for element in elements)

    return (ipv4.compressed, delimiter.join(octets))


def read_stdin():
    """Return elements from standard input, ignoring comments"""
    words = []

    for line in sys.stdin:
        # Be liberal and ignore any line that obviously doesn't
        # contain an IPv4 address — even if that line doesn't
        # conform to the expected format.
        if len(line) < 8:  # '0.0.0.0\n'
            continue
        if line.startswith('#'):
            continue
        if line.count('#') > 0:
            line = line.split('#', 1)[0]

        words += line.split()

    return words


def main(progname=__whoami__):
    """Main entry point"""

    debug('dict', MNEMONICS)
    debug('argv', sys.argv)

    parser = argparse.ArgumentParser(
        prog=progname,
        formatter_class=argparse.RawTextHelpFormatter,
        epilog=EPILOG
    )
    # Generic options
    parser.add_argument('-v', '--version', action='version',
                        version='%(prog)s/{}'.format(__version__),
                        help='show version information and exit')
    parser.add_argument('-c', '--copyright', action='version',
                        version=__copyright__,
                        help='show copying policy and exit')
    # Specific option(s)
    parser.add_argument('-d', '--delimiter', default='-',
                        help='use DELIMITER instead of ‘-’')
    # Optional IPv4 addresses
    parser.add_argument('IPv4', nargs='*', help='IPv4 address')

    args = parser.parse_args()
    debug('args', args)

    cache = set()
    delimiter = args.delimiter

    try:
        addresses = args.IPv4 or read_stdin()
    except KeyboardInterrupt:
        die('')

    if len(addresses) > 1:
        for address in addresses:
            (ipv4, mnemonic) = ip2mne(address, delimiter)
            if ipv4 in cache:
                continue
            cache.add(ipv4)
            print('\t'.join((ipv4, mnemonic)))
    else:
        (_, mnemonic) = ip2mne(addresses[0], delimiter)
        print(mnemonic)

    return 0


if __name__ == '__main__':
    sys.exit(main(pathlib.Path(sys.argv[0]).name))

# eof
